# Generated by Django 4.2.25 on 2025-10-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(default="Prishtina", max_length=120),
        ),
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(default="Prishtina", max_length=120),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="category",
            field=models.CharField(
                choices=[
                    ("restaurant", "Restaurant"),
                    ("bar", "Bar"),
                    ("cafe", "Cafe"),
                    ("dessert", "Dessert"),
                ],
                default="restaurant",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="Prishtina", max_length=120),
        ),
    ]
