# Generated by Django 4.2.25 on 2025-10-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0002_event_city_hotel_city_restaurant_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="country",
            field=models.CharField(
                choices=[("Kosovë", "Kosovë"), ("Shqipëri", "Shqipëri")],
                default="Kosovë",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="country",
            field=models.CharField(
                choices=[("Kosovë", "Kosovë"), ("Shqipëri", "Shqipëri")],
                default="Kosovë",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="country",
            field=models.CharField(
                choices=[("Kosovë", "Kosovë"), ("Shqipëri", "Shqipëri")],
                default="Kosovë",
                max_length=40,
            ),
        ),
    ]
